apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
data:
  secret-key-base: ZmI2MTVlNDUyZjI3NzEyZDM1MDYzYmQzNDQ4Nzc3MWI3NDgxYjAyMDMxOTI2MzkzZmNkMzg3ZTAzZmE4MjA3ZmNiMTM4YWVhZTQyZTA3YTMzOGRiZDIyOTE0NTU1NzJkYjMyZDZiNjlkY2RhZWZjNzIzNjVhMzRhNDUyOWU0MzQ=
