apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: rdalin/docka:v2
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: web-secret
                key: secret-key-base
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: rails
        ports:
        - containerPort: 3000
          protocol: TCP
